### ISSUE TITLE
Should Sample route registration be more transparent

### ISSUE THREAD

**Issue by herskinduk** [Sitecore-Community/Sitecore-Mvc-Contrib#8]
Route registration is done by adding a reference to the SitecoreContribSample assembly. Whilst elegant - it is less than obvious where the route registration is done.
Should we change this to be more clear?

**Comment by kevinobee** [comment]
Any suggestions for alternative implementations?

**Comment by herskinduk** [comment]
Could we just move /App_Start/MvcContribPackage.cs to /content/App_Start/MvcContribPackage.cs and loose the reference to SitecoreMvcContrib.Sample?

**Comment by herskinduk** [comment]
Have a look here:
https://github.com/Sitecore-Community/Sitecore-Mvc-Contrib/tree/dev/childaction-renderer/src/Sitecore.Mvc.Contrib.Sample/content/App_Start

Seems to work just as well. And now the routes can be found in the source code that is being added to your project. I think it adds transparency.

**Comment by herskinduk** [comment]
I have moved MvcContribPackage.cs as per my suggestion above.
