### ISSUE TITLE
Sample project installs unused item

### ISSUE THREAD

**Issue by herskinduk** [Sitecore-Community/Sitecore-Mvc-Contrib#9]
/sitecore/content/Mvc Sample seems to be a leftover and no longer used...

**Comment by kevinobee** [comment]
Mvc Sample is used in the routing for the injector examples
 The routes are set in https://github.com/Sitecore-Community/Sitecore-Mvc-Contrib/blob/master/src/Sitecore.Mvc.Contrib.Sample/App_Start/MvcContribPackage.cs
